version: '3'
services:

  database:
      image: 'postgres:latest'
      ports:
      - 5432:5432
      restart: always
      container_name: database_postgres
      env_file:
      - .env
      build: ./database/
      volumes:
      - ./database/:/var/lib/postgresql/data/



  adminer:
      image: adminer
      restart: always
      depends_on:
      - database
      ports:
      - 8080:8080



  script:
      build: ./
      command: /main.py
      container_name: script
      depends_on:
        - database